.DEFAULT_GOAL := shell

USE_GRAPHICS ?= 1

CONTAINER_CMD = podman
CONTAINER_NAME = gltron
FILES_TO_MOUNT = -v $(shell pwd):/gltron/:Z \
                 -v ./entrypoint/shell.sh:/usr/local/bin/shell.sh:Z \
                 -v ./entrypoint/format.sh:/usr/local/bin/format.sh:Z \
                 -v ./entrypoint/dotfiles/.tmux.conf:/root/.tmux.conf:Z \
                 -v ./entrypoint/dotfiles/.extrabashrc:/root/.extrabashrc:Z



USE_X = -e DISPLAY=$(DISPLAY) \
	-v /tmp/.X11-unix:/tmp/.X11-unix \
	--security-opt label=type:container_runtime_t
WAYLAND_FLAGS_FOR_CONTAINER = -e "WAYLAND_DISPLAY=${WAYLAND_DISPLAY}" \
                              -e "XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}" \
                              -v "${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}"



.PHONY: all
all: shell ## Build the image and get a shell in it

.PHONY: image
image: ## Build podman image (also builds gltron via CMake at image-build time)
	# build the container
	$(CONTAINER_CMD) build \
                         --build-arg BUILD_DOCS=$(BUILD_DOCS) \
                         --build-arg USE_GRAPHICS=$(USE_GRAPHICS) \
                         -t $(CONTAINER_NAME) \
                         .


.PHONY: build
build: image ## Re-run CMake build inside the container against the mounted source tree (writes ./bld)
	$(CONTAINER_CMD) run --rm \
		$(FILES_TO_MOUNT) \
		$(CONTAINER_NAME) \
		bash -lc 'cmake -S /gltron -B /gltron/bld -G Ninja \
		            -DCMAKE_BUILD_TYPE=Debug \
		            -DCMAKE_INSTALL_PREFIX=/gltron/bld/install \
		         && cmake --build /gltron/bld -j \
		         && cmake --install /gltron/bld \
		         && (cd /gltron/bld && ctest --output-on-failure)'


.PHONY: shell
shell:  ## Get Shell into a ephermeral container made from the image
	$(CONTAINER_CMD) run -it --rm \
		--entrypoint /bin/bash \
		$(FILES_TO_MOUNT) \
		$(USE_X) \
		$(WAYLAND_FLAGS_FOR_CONTAINER) \
		$(CONTAINER_NAME) \
		/usr/local/bin/shell.sh



.PHONY: format
format: image ## Format the C code
	$(CONTAINER_CMD) run -it --rm \
		--entrypoint /bin/bash \
		$(FILES_TO_MOUNT) \
		$(USE_X) \
		$(CONTAINER_NAME) \
		/usr/local/bin/format.sh


.PHONY: help
help:
	@grep --extended-regexp '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'
